"""Single source of truth for the Blendkit Unreal plugin version.

Humans edit :data:`BASE_VERSION` (``major.minor``) here — that is the only knob
you normally touch. The **full** version string is

    ``major.minor.YYMMDDHHmm``            (stable / dev)
    ``major.minor.YYMMDDHHmm-alpha``      (automated builds from ``main``)

and is computed at *build time* by ``dev.py`` and written into the generated,
git-ignored ``_build_version.py`` next to this file.

At runtime we prefer that generated file (present in any packaged build). In a
plain source checkout — where no build has run — we fall back to a ``.dev``
string so the plugin still loads and reports something sensible.
"""

from __future__ import annotations

# ── Human-editable knob ───────────────────────────────────────────────────────
BASE_VERSION = "0.1"
"""``major.minor``. Bump by hand when cutting a new minor or major line."""

# ── Release channels ──────────────────────────────────────────────────────────
CHANNEL_STABLE = "stable"
CHANNEL_ALPHA = "alpha"
CHANNEL_DEV = "dev"


def _load_build_info() -> dict[str, str] | None:
    """Return the generated build metadata, or ``None`` in a source checkout."""
    try:
        from . import _build_version as bv  # generated by dev.py at build time
    except Exception:
        return None
    return {
        "version": getattr(bv, "VERSION", ""),
        "channel": getattr(bv, "CHANNEL", ""),
        "build_time": getattr(bv, "BUILD_TIME", ""),
        "git_commit": getattr(bv, "GIT_COMMIT", ""),
    }


def get_version() -> str:
    """Full version string, e.g. ``0.1.2506071430-alpha`` (or ``0.1.dev``)."""
    info = _load_build_info()
    if info and info.get("version"):
        return info["version"]
    return f"{BASE_VERSION}.dev"


def get_channel() -> str:
    """Release channel: ``stable``, ``alpha`` or ``dev`` (unbuilt checkout)."""
    info = _load_build_info()
    if info and info.get("channel"):
        return info["channel"]
    return CHANNEL_DEV


def get_version_info() -> dict[str, str]:
    """Everything callers might want to show in an About/Settings panel."""
    info = _load_build_info() or {}
    return {
        "version": get_version(),
        "channel": get_channel(),
        "base_version": BASE_VERSION,
        "build_time": info.get("build_time", ""),
        "git_commit": info.get("git_commit", ""),
    }


__version__ = get_version()
